buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath libs.stringfog.xor
    }
}

plugins {
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.kotlinAndroid) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.stringfog) apply false
}